### PR TITLE
updated to 3.13 and adds a spinner

### LINKED ISSUE #57: add loading spinner for map
Some services (not naming any names here) take a while.

### LINKED ISSUE #73: Update to JSAPI 3.13
Now [that bootstrap-map-js has](https://github.com/Esri/bootstrap-map-js/pull/136), it's time for this repo to as well.

NOTE: bootstrap map also updated to the latest bootstrap CSS (3.3.2), but [Dojo Bootstrap is still tied to Bootstrap 3.1.1](https://github.com/xsokev/Dojo-Bootstrap#dojo-bootstrap), so will need to test w/ 3.3.2 CSS and if it works be sure to include comments and a note in the README about that. If it doesn't work, the leave the CSS at 3.1.1.

### PR DESCRIPTION
**Pull request by tsamaya**
updated to JSAPI 3.13 thanks to @steveoh and @stdavis (fixes #73)
adds a spinner thanks to @npeihl (fixes #57 and question #83)

### CODE REVIEW

**Comment by tomwayson** [comment]
Thanks so much @tsamaya and @npeihl, you guys rock!

**Comment by tomwayson** [comment]
and of course thanks to @stdavis!

**Comment by tomwayson** [comment]
@tsamaya, be sure to get latest b/c I made a couple changes to your PR: 2934535b0789d47cd71bcc4286b2c7617af0cc90

**Comment by tsamaya** [comment]
Thanks Tom. I have to improve my Bower search :)

2015-03-20 6:07 GMT+01:00 Tom Wayson <notifications@github.com>:

**Comment by stdavis** [comment]
You are very welcome.

On Thu, Mar 19, 2015 at 11:02 PM, Tom Wayson <notifications@github.com>
wrote:

> and of course thanks to @stdavis <https://github.com/stdavis>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/dojo-bootstrap-map-js/pull/86#issuecomment-83904478>
> .
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by tsamaya** [comment]
I have just found `bower list` : the magic command!

```
d:\AFE\GitHub\tsamaya\dojo-bootstrap-map-js>bower list
bower check-new     Checking for new versions of the project dependencies..
dojo-bootstrap-map-js#3.2.2 d:\AFE\GitHub\tsamaya\dojo-bootstrap-map-js
├── bootstrap-map-js#0.0.2
├── dgrid#0.3.17 (latest is 0.4.0)
├── dijit#1.10.2 (latest is 1.10.4)
├── dojo#1.10.4
├── dojo-bootstrap#3.0.2
├── dojox#1.10.2 (latest is 1.10.4)
├── put-selector#0.3.6
├── spinjs#2.0.1 (latest is 2.0.2)
├── util#1.10.2 (latest is 1.10.4)
└── xstyle#0.1.3 (latest is 0.3.1)
```

**Pull request merged**
